export const introStickers = [
  { code: '00', name: 'Panini Logo' },
  { code: 'FWC1', name: 'Official Emblem' },
  { code: 'FWC2', name: 'Official Emblem' },
  { code: 'FWC3', name: 'Official Mascots' },
  { code: 'FWC4', name: 'Official Slogan' },
  { code: 'FWC5', name: 'Official Ball' },
  { code: 'FWC6', name: 'Canada - Host Countries & Cities' },
  { code: 'FWC7', name: 'Mexico - Host Countries & Cities' },
  { code: 'FWC8', name: 'USA - Host Countries & Cities' },
];

export const worldCupHistory = [
  { code: 'FWC9', name: 'Italy 1934' },
  { code: 'FWC10', name: 'Uruguay 1950' },
  { code: 'FWC11', name: 'West Germany 1954' },
  { code: 'FWC12', name: 'Brazil 1962' },
  { code: 'FWC13', name: 'West Germany 1974' },
  { code: 'FWC14', name: 'Argentina 1986' },
  { code: 'FWC15', name: 'Brazil 1994' },
  { code: 'FWC16', name: 'Brazil 2002' },
  { code: 'FWC17', name: 'Italy 2006' },
  { code: 'FWC18', name: 'Germany 2014' },
  { code: 'FWC19', name: 'Argentina 2022' },
];

export const teams = [
  'Mexico', 'Canada', 'USA', 'Algeria', 'Argentina', 'Australia', 'Austria',
  'Belgium', 'Bosnia and Herzegovina', 'Brazil', 'Cape Verde', 'Colombia',
  'Congo DR', 'Croatia', 'Curaçao', 'Czechia', 'Ecuador', 'Egypt', 'England',
  'France', 'Germany', 'Ghana', 'Haiti', 'Iran', 'Iraq', 'Ivory Coast', 'Japan',
  'Jordan', 'Morocco', 'Netherlands', 'New Zealand', 'Norway', 'Panama',
  'Paraguay', 'Portugal', 'Qatar', 'Saudi Arabia', 'Scotland', 'Senegal',
  'South Africa', 'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Tunisia',
  'Türkiye', 'Uruguay', 'Uzbekistan',
];

export const teamCodes = {
  Mexico: 'MEX',
  Canada: 'CAN',
  USA: 'USA',
  Algeria: 'ALG',
  Argentina: 'ARG',
  Australia: 'AUS',
  Austria: 'AUT',
  Belgium: 'BEL',
  'Bosnia and Herzegovina': 'BIH',
  Brazil: 'BRA',
  'Cape Verde': 'CPV',
  Colombia: 'COL',
  'Congo DR': 'COD',
  Croatia: 'CRO',
  Curaçao: 'CUW',
  Czechia: 'CZE',
  Ecuador: 'ECU',
  Egypt: 'EGY',
  England: 'ENG',
  France: 'FRA',
  Germany: 'GER',
  Ghana: 'GHA',
  Haiti: 'HAI',
  Iran: 'IRN',
  Iraq: 'IRQ',
  'Ivory Coast': 'CIV',
  Japan: 'JPN',
  Jordan: 'JOR',
  Morocco: 'MAR',
  Netherlands: 'NED',
  'New Zealand': 'NZL',
  Norway: 'NOR',
  Panama: 'PAN',
  Paraguay: 'PAR',
  Portugal: 'POR',
  Qatar: 'QAT',
  'Saudi Arabia': 'KSA',
  Scotland: 'SCO',
  Senegal: 'SEN',
  'South Africa': 'RSA',
  'South Korea': 'KOR',
  Spain: 'ESP',
  Sweden: 'SWE',
  Switzerland: 'SUI',
  Tunisia: 'TUN',
  Türkiye: 'TUR',
  Uruguay: 'URU',
  Uzbekistan: 'UZB',
};
